# Generated by Django 4.1.5 on 2023-01-08 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('first_line_address', models.CharField(max_length=255)),
                ('second_line_address', models.CharField(max_length=255)),
                ('postocde', models.CharField(max_length=255)),
                ('town_or_city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lease_agreement_file', models.FileField(upload_to='')),
                ('rent_protection_policy_file', models.FileField(upload_to='')),
                ('tenant_vetting_file', models.FileField(upload_to='')),
                ('amount_of_rent_selling', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_monthly_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name_on_bank_account', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('sort_code_bank_account', models.CharField(max_length=100)),
            ],
        ),
    ]
