# Generated by Django 4.1.5 on 2023-01-08 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
